-- Bulk insert participants for NCS 55th AGM
-- Categories: delegate (doctors/professors), exhibitor (Allied), guest (Medical Students, Associates)

INSERT INTO public.participants (full_name, email, category, organisation) VALUES
('Prof Augustine Odili', 'augustine.odili@ncs-eko2026.local', 'delegate', NULL),
('Prof Kamilu Karaye', 'kamilu.karaye@ncs-eko2026.local', 'delegate', NULL),
('Prof Chizindu Alikor', 'chizindu.alikor@ncs-eko2026.local', 'delegate', NULL),
('Prof Ejiroghene Umuerri', 'ejiroghene.umuerri@ncs-eko2026.local', 'delegate', NULL),
('Dr. Quennette Daniels', 'quennette.daniels@ncs-eko2026.local', 'delegate', NULL),
('Prof Adeseye Akintunde', 'adeseye.akintunde@ncs-eko2026.local', 'delegate', NULL),
('Prof. Okechukwu Ogah', 'okechukwu.ogah@ncs-eko2026.local', 'delegate', NULL),
('Dr Folasade Daniel', 'folasade.daniel@ncs-eko2026.local', 'delegate', NULL),
('Dr Adeola Olubunmi Ajibare', 'adeola.ajibare@ncs-eko2026.local', 'delegate', NULL),
('Prof John Okeniyi', 'john.okeniyi@ncs-eko2026.local', 'delegate', NULL),
('Prof Olayinka Akinwusi', 'olayinka.akinwusi@ncs-eko2026.local', 'delegate', NULL),
('Dr Timothy Folorunso', 'timothy.folorunso@ncs-eko2026.local', 'delegate', NULL),
('Mr Onyekwelu Nzewi', 'onyekwelu.nzewi@ncs-eko2026.local', 'delegate', NULL),
('Dr Olalekan Adesokan', 'olalekan.adesokan@ncs-eko2026.local', 'delegate', NULL),
('Prof Rasaaq Adebayo', 'rasaaq.adebayo@ncs-eko2026.local', 'delegate', NULL),
('Prof Adeola Animasaun', 'adeola.animasaun@ncs-eko2026.local', 'delegate', NULL),
('Maj Gen Life Ajemba', 'life.ajemba@ncs-eko2026.local', 'delegate', NULL),
('Prof Emmanuel Onwubuya', 'emmanuel.onwubuya@ncs-eko2026.local', 'delegate', NULL),
('Prof Muhammad Sani Isa', 'muhammad.isa@ncs-eko2026.local', 'delegate', NULL),
('Prof Phillip Alaba Adebola', 'phillip.adebola@ncs-eko2026.local', 'delegate', NULL),
('Dr Chukwudi Nwagbara', 'chukwudi.nwagbara@ncs-eko2026.local', 'delegate', NULL),
('Dr Cressida Amichoh', 'cressida.amichoh@ncs-eko2026.local', 'delegate', NULL),
('Dr Julius Adesina', 'julius.adesina@ncs-eko2026.local', 'delegate', NULL),
('Prof Chibuike Eze Nwafor', 'chibuike.nwafor@ncs-eko2026.local', 'delegate', NULL),
('Mrs Alake Aina', 'alake.aina@ncs-eko2026.local', 'delegate', NULL),
('Dr Alaba Oladimeji', 'alaba.oladimeji@ncs-eko2026.local', 'delegate', NULL),
('Prof Sotonye Dodiyi-Manuel', 'sotonye.dodiyi-manuel@ncs-eko2026.local', 'delegate', NULL),
('Dr Folashade Toluhi', 'folashade.toluhi@ncs-eko2026.local', 'delegate', NULL),
('Dr Sabiu Mohammed Hamza', 'sabiu.hamza@ncs-eko2026.local', 'delegate', NULL),
('Dr Olubukola Ransome-Kuti', 'olubukola.ransome-kuti@ncs-eko2026.local', 'delegate', NULL),
('Dr Folasade Alli', 'folasade.alli@ncs-eko2026.local', 'delegate', NULL),
('Dr Chimezie Udennaka', 'chimezie.udennaka@ncs-eko2026.local', 'delegate', NULL),
('Dr Omolola Lamina', 'omolola.lamina@ncs-eko2026.local', 'delegate', NULL),
('Dr Ramon Moronkola', 'ramon.moronkola@ncs-eko2026.local', 'delegate', NULL),
('Dr Akinyemi Aje', 'akinyemi.aje@ncs-eko2026.local', 'delegate', NULL),
('Dr Charles Okorie', 'charles.okorie@ncs-eko2026.local', 'delegate', NULL),
('Dr Obasanjo Adebiyi', 'obasanjo.adebiyi@ncs-eko2026.local', 'delegate', NULL),
('Prof Uchenna Onubogu', 'uchenna.onubogu@ncs-eko2026.local', 'delegate', NULL),
('Dr Paschal Njoku', 'paschal.njoku@ncs-eko2026.local', 'delegate', NULL),
('Dr Aisosa Ogbomo', 'aisosa.ogbomo@ncs-eko2026.local', 'delegate', NULL),
('Mr Osagie-Shawn Ogbomo', 'osagie-shawn.ogbomo@ncs-eko2026.local', 'guest', 'Medical Student'),
('Dr Babajide Ojo', 'babajide.ojo@ncs-eko2026.local', 'delegate', NULL),
('Dr David Davou Nyam', 'david.nyam@ncs-eko2026.local', 'delegate', NULL),
('Dr Abdulazeez Olanrewaju', 'abdulazeez.olanrewaju@ncs-eko2026.local', 'delegate', NULL),
('Dr Atinuke Richard', 'atinuke.richard@ncs-eko2026.local', 'delegate', NULL),
('Dr Muhammad Nazir Shehu', 'muhammad.shehu@ncs-eko2026.local', 'delegate', NULL),
('Dr Ijeoma Ajoku', 'ijeoma.ajoku@ncs-eko2026.local', 'delegate', NULL),
('Prof Wilson Sadoh', 'wilson.sadoh@ncs-eko2026.local', 'delegate', NULL),
('Dr Olatunji Bukola Olaoye', 'olatunji.olaoye@ncs-eko2026.local', 'delegate', NULL),
('Dr Quazim Ismail', 'quazim.ismail@ncs-eko2026.local', 'delegate', NULL),
('Dr Assumpta Aham', 'assumpta.aham@ncs-eko2026.local', 'delegate', NULL),
('Dr Emmanuel Ovundah Nyeche', 'emmanuel.nyeche@ncs-eko2026.local', 'delegate', NULL),
('Dr Ojiaku Lilian Ifechukwude', 'ojiaku.ifechukwude@ncs-eko2026.local', 'delegate', NULL),
('Dr Florence Briggs', 'florence.briggs@ncs-eko2026.local', 'delegate', NULL),
('Dr Ike Kenechukwu', 'ike.kenechukwu@ncs-eko2026.local', 'delegate', NULL),
('Dr Sadiq Ringim', 'sadiq.ringim@ncs-eko2026.local', 'delegate', NULL),
('Dr Aisosa Olaniyonu', 'aisosa.olaniyonu@ncs-eko2026.local', 'delegate', NULL),
('Dr Asmau Belko Nuruddeen', 'asmau.nuruddeen@ncs-eko2026.local', 'delegate', NULL),
('Dr Wasiu Muritala', 'wasiu.muritala@ncs-eko2026.local', 'delegate', NULL),
('Mr Quadri Erinjogunola', 'quadri.erinjogunola@ncs-eko2026.local', 'delegate', NULL),
('Dr Owhoavwodua Precious', 'owhoavwodua.precious@ncs-eko2026.local', 'delegate', NULL),
('Dr Oluwaseyi Olorunfemi', 'oluwaseyi.olorunfemi@ncs-eko2026.local', 'delegate', NULL),
('Prof Uvie Onakpoya', 'uvie.onakpoya@ncs-eko2026.local', 'delegate', NULL),
('Dr Chineme Ekeh', 'chineme.ekeh@ncs-eko2026.local', 'delegate', NULL),
('Dr Toyyeb Oladipo', 'toyyeb.oladipo@ncs-eko2026.local', 'delegate', NULL),
('Dr Oghenevwarhe Asore', 'oghenevwarhe.asore@ncs-eko2026.local', 'delegate', NULL),
('Dr Olumide Akinyele', 'olumide.akinyele@ncs-eko2026.local', 'delegate', NULL),
('Prof Balarabe Garko Sani', 'balarabe.sani@ncs-eko2026.local', 'delegate', NULL),
('Dr Suraj Ogunyemi', 'suraj.ogunyemi@ncs-eko2026.local', 'delegate', NULL),
('Dr Boma Oyan', 'boma.oyan@ncs-eko2026.local', 'delegate', NULL),
('Dr Tolulope Shogade', 'tolulope.shogade@ncs-eko2026.local', 'delegate', NULL),
('Prof Olufemi Ajayi', 'olufemi.ajayi@ncs-eko2026.local', 'delegate', NULL),
('Dr Okechukwu Usim', 'okechukwu.usim@ncs-eko2026.local', 'delegate', NULL),
('Dr Francisca Inofomoh', 'francisca.inofomoh@ncs-eko2026.local', 'delegate', NULL),
('Dr Chokor Felix', 'chokor.felix@ncs-eko2026.local', 'delegate', NULL),
('Dr Nonye Oputa', 'nonye.oputa@ncs-eko2026.local', 'delegate', NULL),
('Dr Chibundo Nwaneli', 'chibundo.nwaneli@ncs-eko2026.local', 'delegate', NULL),
('Dr Tawfiq Yusuf', 'tawfiq.yusuf@ncs-eko2026.local', 'delegate', NULL),
('Dr Cassidy Ibeh', 'cassidy.ibeh@ncs-eko2026.local', 'delegate', NULL),
('Dr Nnenna Lawrentia Okoroafor', 'nnenna.okoroafor@ncs-eko2026.local', 'delegate', NULL),
('Dr Busayo Oguntola', 'busayo.oguntola@ncs-eko2026.local', 'delegate', NULL),
('Dr Leonard Okorie', 'leonard.okorie@ncs-eko2026.local', 'delegate', NULL),
('Prof Innocent Okoye', 'innocent.okoye@ncs-eko2026.local', 'delegate', NULL),
('Anne Okoye', 'anne.okoye@ncs-eko2026.local', 'delegate', NULL),
('Dr Godwin Udoh', 'godwin.udoh@ncs-eko2026.local', 'delegate', NULL),
('Dr Burabari Kemsi', 'burabari.kemsi@ncs-eko2026.local', 'delegate', NULL),
('Dr Veronica Josephs', 'veronica.josephs@ncs-eko2026.local', 'delegate', NULL),
('Dr Olumuyiwa Folayan', 'olumuyiwa.folayan@ncs-eko2026.local', 'delegate', NULL),
('Dr Faith Chikani', 'faith.chikani@ncs-eko2026.local', 'delegate', NULL),
('Prof Ebenezer Ajayi', 'ebenezer.ajayi@ncs-eko2026.local', 'delegate', NULL),
('Dr Celestine Okwara', 'celestine.okwara@ncs-eko2026.local', 'delegate', NULL),
('Dr Nkiruka Nwagbara', 'nkiruka.nwagbara@ncs-eko2026.local', 'delegate', NULL),
('Dr Augustine Odanye', 'augustine.odanye@ncs-eko2026.local', 'delegate', NULL),
('Dr Esther Ohihoin', 'esther.ohihoin@ncs-eko2026.local', 'delegate', NULL),
('Mrs Modupe Valentina Olufisoye', 'modupe.olufisoye@ncs-eko2026.local', 'delegate', NULL),
('Dr Jennifer Oji', 'jennifer.oji@ncs-eko2026.local', 'delegate', NULL),
('Dr Thomas Irabor', 'thomas.irabor@ncs-eko2026.local', 'delegate', NULL),
('Dr Olufisayo Adesina', 'olufisayo.adesina@ncs-eko2026.local', 'delegate', NULL),
('Dr Olayinka Hassan', 'olayinka.hassan@ncs-eko2026.local', 'delegate', NULL),
('Dr Abubakar Maaji Ahmad', 'abubakar.ahmad@ncs-eko2026.local', 'delegate', NULL),
('Dr Olalekan Olakanye', 'olalekan.olakanye@ncs-eko2026.local', 'delegate', NULL),
('Onyinyechukwu Odimegwu', 'onyinyechukwu.odimegwu@ncs-eko2026.local', 'guest', 'Medical Student'),
('Dr Rilwan Adegboyega Oyekunle', 'rilwan.oyekunle@ncs-eko2026.local', 'delegate', NULL),
('Dr Ojuolape Okedara', 'ojuolape.okedara@ncs-eko2026.local', 'delegate', NULL),
('Dr Henry Ifeanyichukwu Okolie', 'henry.okolie@ncs-eko2026.local', 'delegate', NULL),
('Dr Philomena Ikeanisi', 'philomena.ikeanisi@ncs-eko2026.local', 'delegate', NULL),
('Dr Bakare Ayodeji', 'bakare.ayodeji@ncs-eko2026.local', 'delegate', NULL),
('Dr Ifeoma Ilona', 'ifeoma.ilona@ncs-eko2026.local', 'delegate', NULL),
('Dr Izibekian Evans Luke', 'izibekian.luke@ncs-eko2026.local', 'delegate', NULL),
('Dr Adedeji Adebayo', 'adedeji.adebayo@ncs-eko2026.local', 'delegate', NULL),
('Dr Ugomma Amobi', 'ugomma.amobi@ncs-eko2026.local', 'delegate', NULL),
('Prof. Ehimwenma Ogbemudia', 'ehimwenma.ogbemudia@ncs-eko2026.local', 'delegate', NULL),
('Dr Samuel Orji', 'samuel.orji@ncs-eko2026.local', 'delegate', NULL),
('Dr Oladimeji Adebayo', 'oladimeji.adebayo@ncs-eko2026.local', 'delegate', NULL),
('Dr Ezinne Nwaneli', 'ezinne.nwaneli@ncs-eko2026.local', 'delegate', NULL),
('Dr Anuoluwapo Makinde', 'anuoluwapo.makinde@ncs-eko2026.local', 'delegate', NULL),
('Dr Bosede Iyapo', 'bosede.iyapo@ncs-eko2026.local', 'delegate', NULL),
('Dr Onyinye Olive Egwim', 'onyinye.egwim@ncs-eko2026.local', 'delegate', NULL),
('Dr Obuoma Amaewhule', 'obuoma.amaewhule@ncs-eko2026.local', 'delegate', NULL),
('Dr Maduka Okoroafor', 'maduka.okoroafor@ncs-eko2026.local', 'delegate', NULL),
('Dr Ngozi Onwueme', 'ngozi.onwueme@ncs-eko2026.local', 'delegate', NULL),
('Adedayo Okewale', 'adedayo.okewale@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Peter Oladapo Adeoye', 'peter.adeoye@ncs-eko2026.local', 'delegate', NULL),
('Dr Olaniyi James Bamikole', 'olaniyi.bamikole@ncs-eko2026.local', 'delegate', NULL),
('Dr Habib Maji Muhammad', 'habib.muhammad@ncs-eko2026.local', 'delegate', NULL),
('Prof Emmanuel Ejim', 'emmanuel.ejim@ncs-eko2026.local', 'delegate', NULL),
('Dr Olajide Oladeji', 'olajide.oladeji@ncs-eko2026.local', 'delegate', NULL),
('Dr Aghogho Omajuwa', 'aghogho.omajuwa@ncs-eko2026.local', 'delegate', NULL),
('Dr Chinedum Eluogu', 'chinedum.eluogu@ncs-eko2026.local', 'delegate', NULL),
('Dr Akinwumi Ojo', 'akinwumi.ojo@ncs-eko2026.local', 'delegate', NULL),
('Dr Doommaren Awunah', 'doommaren.awunah@ncs-eko2026.local', 'delegate', NULL),
('Dr Ramatu Aliyu-zubair', 'ramatu.aliyu-zubair@ncs-eko2026.local', 'delegate', NULL),
('Dr Olugbenga Abiodun', 'olugbenga.abiodun@ncs-eko2026.local', 'delegate', NULL),
('Zainab Titilope Adetunji', 'zainab.adetunji@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Halima Bello', 'halima.bello@ncs-eko2026.local', 'delegate', NULL),
('Dr Chioma Tochukwu-Onyejieme', 'chioma.onyejieme@ncs-eko2026.local', 'delegate', NULL),
('Dr Nwawuefe SOYELE', 'nwawuefe.soyele@ncs-eko2026.local', 'delegate', NULL),
('Dr Peter Chinenye Mba', 'peter.mba@ncs-eko2026.local', 'delegate', NULL),
('Dr Chinonye Awkadigwe', 'chinonye.awkadigwe@ncs-eko2026.local', 'delegate', NULL),
('Dr Olugbenga Ojo', 'olugbenga.ojo@ncs-eko2026.local', 'delegate', NULL),
('Dr Maryam Usman', 'maryam.usman@ncs-eko2026.local', 'delegate', NULL),
('Dr Caroline Ajuyah', 'caroline.ajuyah@ncs-eko2026.local', 'delegate', NULL),
('Dr Vincent Ofuonye', 'vincent.ofuonye@ncs-eko2026.local', 'delegate', NULL),
('Dr Ukamaka Blessing Ugwoke', 'ukamaka.ugwoke@ncs-eko2026.local', 'delegate', NULL),
('Dr Nuruddeen Mohammed', 'nuruddeen.mohammed@ncs-eko2026.local', 'delegate', NULL),
('Dr Oluseyi Adegoke', 'oluseyi.adegoke@ncs-eko2026.local', 'delegate', NULL),
('Professor Victor Ansa', 'victor.ansa@ncs-eko2026.local', 'delegate', NULL),
('Dr Etubi Ibrahim', 'etubi.ibrahim@ncs-eko2026.local', 'delegate', NULL),
('OLUWAPELUMI BABARINDE', 'oluwapelumi.babarinde@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Vandi Zira Ghyi', 'vandi.ghyi@ncs-eko2026.local', 'delegate', NULL),
('Dr Shaima Ahmad Abdel-Sadiq', 'shaima.abdel-sadiq@ncs-eko2026.local', 'delegate', NULL),
('Dr Isa Abiodun Makinde', 'isa.makinde@ncs-eko2026.local', 'delegate', NULL),
('Dr. Chioma Nwabunike', 'chioma.nwabunike@ncs-eko2026.local', 'delegate', NULL),
('Dr Apollos DANIEL', 'apollos.daniel@ncs-eko2026.local', 'delegate', NULL),
('Goodness Animasahun', 'goodness.animasahun@ncs-eko2026.local', 'guest', 'Medical Student'),
('Dr Olanike Orimolade', 'olanike.orimolade@ncs-eko2026.local', 'delegate', NULL),
('Dr Yahaya Baba Adamu', 'yahaya.adamu@ncs-eko2026.local', 'delegate', NULL),
('Dr Chimaroke Chikeka', 'chimaroke.chikeka@ncs-eko2026.local', 'delegate', NULL),
('Dr Adaobi Ofordile', 'adaobi.ofordile@ncs-eko2026.local', 'delegate', NULL),
('Dr Ese Gift Adjarho', 'ese.adjarho@ncs-eko2026.local', 'delegate', NULL),
('Dr Abubakar Usman', 'abubakar.usman@ncs-eko2026.local', 'delegate', NULL),
('Dr KINGSLEY AKHERE', 'kingsley.akhere@ncs-eko2026.local', 'delegate', NULL),
('Dr CHIOMA CHUKWUEMEKA', 'chioma.chukwuemeka@ncs-eko2026.local', 'delegate', NULL),
('Dr Taiwo Adedokun', 'taiwo.adedokun@ncs-eko2026.local', 'delegate', NULL),
('Dr Nnedinma Epuechi', 'nnedinma.epuechi@ncs-eko2026.local', 'delegate', NULL),
('Dr Chiamaka Obiukwu', 'chiamaka.obiukwu@ncs-eko2026.local', 'delegate', NULL),
('Dr Adejoh Okai', 'adejoh.okai@ncs-eko2026.local', 'delegate', NULL),
('Dr OGHENETEGA EJIFE', 'oghenetega.ejife@ncs-eko2026.local', 'delegate', NULL),
('Dr Ayodeji stephen Adekolade', 'ayodeji.adekolade@ncs-eko2026.local', 'delegate', NULL),
('Dr VERONICA ADEFUNKE OBASUYI', 'veronica.obasuyi@ncs-eko2026.local', 'delegate', NULL),
('Dr Nkeiruka Mbadiwe', 'nkeiruka.mbadiwe@ncs-eko2026.local', 'delegate', NULL),
('Dr OSITA IROKANSI', 'osita.irokansi@ncs-eko2026.local', 'delegate', NULL),
('Dr TEMPLE BASSEY', 'temple.bassey@ncs-eko2026.local', 'delegate', NULL),
('Dr Ebele Ojih', 'ebele.ojih@ncs-eko2026.local', 'delegate', NULL),
('Dr Geoffrey Chibuzor Nwuruku', 'geoffrey.nwuruku@ncs-eko2026.local', 'delegate', NULL),
('Dr Adebimpe Afolabi', 'adebimpe.afolabi@ncs-eko2026.local', 'delegate', NULL),
('Dr NONYE OKONKWO', 'nonye.okonkwo@ncs-eko2026.local', 'delegate', NULL),
('Prof Amam Mbakwem', 'amam.mbakwem@ncs-eko2026.local', 'delegate', NULL),
('Dr SAMUEL UGWU', 'samuel.ugwu@ncs-eko2026.local', 'delegate', NULL),
('Dr Nneka Udora', 'nneka.udora@ncs-eko2026.local', 'delegate', NULL),
('Prof Janet Ngozi Ajuluchukwu', 'janet.ajuluchukwu@ncs-eko2026.local', 'delegate', NULL),
('Dr Omachi Paul', 'omachi.paul@ncs-eko2026.local', 'delegate', NULL),
('Dr Osaretin John Osarenkhoe', 'osaretin.osarenkhoe@ncs-eko2026.local', 'delegate', NULL),
('Dr NOAH ADERINTO', 'noah.aderinto@ncs-eko2026.local', 'delegate', NULL),
('Dr Fredrick Aigbe', 'fredrick.aigbe@ncs-eko2026.local', 'delegate', NULL),
('Esther Yinusa', 'esther.yinusa@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Jeremiah Oiganji', 'jeremiah.oiganji@ncs-eko2026.local', 'delegate', NULL),
('Dr Francis Chidiebere Asogwa', 'francis.asogwa@ncs-eko2026.local', 'delegate', NULL),
('Dr Johnbull Akerele', 'johnbull.akerele@ncs-eko2026.local', 'delegate', NULL),
('Dr Caleb Amaefuna', 'caleb.amaefuna@ncs-eko2026.local', 'delegate', NULL),
('Dr Olabisi Faboyinde', 'olabisi.faboyinde@ncs-eko2026.local', 'delegate', NULL),
('Prof. Faruk BUBA', 'faruk.buba@ncs-eko2026.local', 'delegate', NULL),
('Peter OGUNBOYEDE', 'peter.ogunboyede@ncs-eko2026.local', 'guest', 'Medical Student'),
('Dr Mariam Olutunde', 'mariam.olutunde@ncs-eko2026.local', 'delegate', NULL),
('Dr Oghenetega Akhigbe-Oboh', 'oghenetega.akhigbe-oboh@ncs-eko2026.local', 'delegate', NULL),
('Dr Chuka Onyema', 'chuka.onyema@ncs-eko2026.local', 'delegate', NULL),
('Abdulmal8k Barika', 'abdulmalik.barika@ncs-eko2026.local', 'guest', 'Medical Student'),
('Prof. Hadiza Saidu', 'hadiza.saidu@ncs-eko2026.local', 'delegate', NULL),
('Dr Mohammed Sani Abubakar', 'mohammed.abubakar@ncs-eko2026.local', 'delegate', NULL),
('Dr Oyewole Kushimo', 'oyewole.kushimo@ncs-eko2026.local', 'delegate', NULL),
('Dr Akinsanya Olusegun-Joseph', 'akinsanya.olusegun-joseph@ncs-eko2026.local', 'delegate', NULL),
('Ikhmat Malik', 'ikhmat.malik@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Yekeen Ayodele Ayoola', 'yekeen.ayoola@ncs-eko2026.local', 'delegate', NULL),
('Dr Lukman Tiamiyu', 'lukman.tiamiyu@ncs-eko2026.local', 'delegate', NULL),
('Dr Ikenna Nwafor', 'ikenna.nwafor@ncs-eko2026.local', 'delegate', NULL),
('Dr Valentine''s Amadi', 'valentines.amadi@ncs-eko2026.local', 'delegate', NULL),
('Dr Cosmas Ejide', 'cosmas.ejide@ncs-eko2026.local', 'delegate', NULL),
('Dr Muzzammil Yakasai', 'muzzammil.yakasai@ncs-eko2026.local', 'delegate', NULL),
('Dr Taiwo Olunuga', 'taiwo.olunuga@ncs-eko2026.local', 'delegate', NULL),
('Dr Jibril Muhammed', 'jibril.muhammed@ncs-eko2026.local', 'delegate', NULL),
('Dr Aqib Oloso', 'aqib.oloso@ncs-eko2026.local', 'delegate', NULL),
('Anointing Arthur', 'anointing.arthur@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Olukemi Bamigboye-Taiwo', 'olukemi.bamigboye-taiwo@ncs-eko2026.local', 'delegate', NULL),
('Dr AQUAOWO UDOSEN', 'aquaowo.udosen@ncs-eko2026.local', 'delegate', NULL),
('Mrs Khadijah Opeloyeru-Ajimotokan', 'khadijah.opeloyeru@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Affiong Bassey', 'affiong.bassey@ncs-eko2026.local', 'delegate', NULL),
('Dr Mohammed Bashir Umoru', 'mohammed.umoru@ncs-eko2026.local', 'delegate', NULL),
('Dr Caroline Wonang', 'caroline.wonang@ncs-eko2026.local', 'delegate', NULL),
('Dr A.Temilade Adeyanju', 'atemilade.adeyanju@ncs-eko2026.local', 'delegate', NULL),
('Miracle Victor', 'miracle.victor@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Oni Opeyemi', 'oni.opeyemi@ncs-eko2026.local', 'delegate', NULL),
('Dr Ephraim Uchenna Alor', 'ephraim.alor@ncs-eko2026.local', 'delegate', NULL),
('Dr Ehimen OKOGUN', 'ehimen.okogun@ncs-eko2026.local', 'delegate', NULL),
('Dr Gbolade Lasisi', 'gbolade.lasisi@ncs-eko2026.local', 'delegate', NULL),
('Prof Petronila Tabansi', 'petronila.tabansi@ncs-eko2026.local', 'delegate', NULL),
('Dr ROSEMARY OLUCHI STANLEY', 'rosemary.stanley@ncs-eko2026.local', 'delegate', NULL),
('Prof Fortune Ujunwa', 'fortune.ujunwa@ncs-eko2026.local', 'delegate', NULL),
('Dr Okwudili Jude Ugwuanyi', 'okwudili.ugwuanyi@ncs-eko2026.local', 'delegate', NULL),
('Dr Freedom Enerho', 'freedom.enerho@ncs-eko2026.local', 'delegate', NULL),
('Dr Christiana Alagbe', 'christiana.alagbe@ncs-eko2026.local', 'delegate', NULL),
('Dr Aisien Osaretin', 'aisien.osaretin@ncs-eko2026.local', 'delegate', NULL),
('Dr Temitope Adeolu', 'temitope.adeolu@ncs-eko2026.local', 'delegate', NULL),
('Dr Mojisola Adegbite', 'mojisola.adegbite@ncs-eko2026.local', 'delegate', NULL),
('Dr Rita WAKAMA', 'rita.wakama@ncs-eko2026.local', 'delegate', NULL),
('Prof Christopher Yilgwan', 'christopher.yilgwan@ncs-eko2026.local', 'delegate', NULL),
('Elizabeth Tomilola Emmanuel', 'elizabeth.emmanuel@ncs-eko2026.local', 'delegate', NULL),
('Dr AISHA TUKUR', 'aisha.tukur@ncs-eko2026.local', 'delegate', NULL),
('Dr Samuel Chikaodili Nwafor', 'samuel.nwafor@ncs-eko2026.local', 'delegate', NULL),
('Dr Fidelis Fabopregha', 'fidelis.fabopregha@ncs-eko2026.local', 'delegate', NULL),
('Dr Rukayat Lawan', 'rukayat.lawan@ncs-eko2026.local', 'delegate', NULL),
('Dr Ebikon Igbapike', 'ebikon.igbapike@ncs-eko2026.local', 'delegate', NULL),
('Dr Oyinkansola Tolulope Agaja', 'oyinkansola.agaja@ncs-eko2026.local', 'delegate', NULL),
('Dr Aisha Ajala', 'aisha.ajala@ncs-eko2026.local', 'delegate', NULL),
('Dr Olufemi Ayodele', 'olufemi.ayodele@ncs-eko2026.local', 'delegate', NULL),
('Prof Innocent Okoye', 'innocent.okoye2@ncs-eko2026.local', 'delegate', NULL),
('Dr IFEANYICHUKWU OKOLO', 'ifeanyichukwu.okolo@ncs-eko2026.local', 'delegate', NULL),
('Dr OGOKE LILIAN', 'ogoke.lilian@ncs-eko2026.local', 'delegate', NULL),
('Prof Ekanem Ekure', 'ekanem.ekure@ncs-eko2026.local', 'delegate', NULL),
('Dr Olusegun Adegbaye', 'olusegun.adegbaye@ncs-eko2026.local', 'delegate', NULL),
('Dr Samuel Antia', 'samuel.antia@ncs-eko2026.local', 'delegate', NULL),
('Solomon Aborisade', 'solomon.aborisade@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Prof SOLOMON DANBAUCHI', 'solomon.danbauchi@ncs-eko2026.local', 'delegate', NULL),
('Dr Finine Caroline Penawei', 'finine.penawei@ncs-eko2026.local', 'delegate', NULL),
('Dr ZAKIYYAH ZAKARIYYA', 'zakiyyah.zakariyya@ncs-eko2026.local', 'delegate', NULL),
('Dr Patrick Idoko', 'patrick.idoko@ncs-eko2026.local', 'delegate', NULL),
('Dr OPYOTU AWODI', 'opyotu.awodi@ncs-eko2026.local', 'delegate', NULL),
('Dr Chibuzo Ajaero', 'chibuzo.ajaero@ncs-eko2026.local', 'delegate', NULL),
('Prof MACLEAN AKPA', 'maclean.akpa@ncs-eko2026.local', 'delegate', NULL),
('Dr Aisha Dankaka', 'aisha.dankaka@ncs-eko2026.local', 'delegate', NULL),
('Prof Bode Falase', 'bode.falase@ncs-eko2026.local', 'delegate', NULL),
('Dr Ishaq Aliyaro', 'ishaq.aliyaro@ncs-eko2026.local', 'delegate', NULL),
('Dr Joy Oshun', 'joy.oshun@ncs-eko2026.local', 'delegate', NULL),
('Prof DIKE OJJI', 'dike.ojji@ncs-eko2026.local', 'delegate', NULL),
('Dr Chinazor Nnemelu', 'chinazor.nnemelu@ncs-eko2026.local', 'delegate', NULL),
('Dr NNAEMEKA OGBETE', 'nnaemeka.ogbete@ncs-eko2026.local', 'delegate', NULL),
('Dr Ifejiofor Eberechukwu', 'ifejiofor.eberechukwu@ncs-eko2026.local', 'delegate', NULL),
('Dr Olugbenga Olusoji', 'olugbenga.olusoji@ncs-eko2026.local', 'delegate', NULL),
('Dr Sumaila Ahmodu', 'sumaila.ahmodu@ncs-eko2026.local', 'delegate', NULL),
('Dr Esere Obodo', 'esere.obodo@ncs-eko2026.local', 'delegate', NULL),
('Dr Emmanuel Adeyemi', 'emmanuel.adeyemi@ncs-eko2026.local', 'delegate', NULL),
('Grace Antia', 'grace.antia@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Yuh Nabi Ida', 'yuhnabi.ida@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Agnes Inyam', 'agnes.inyam@ncs-eko2026.local', 'delegate', NULL),
('Dr Mirabel Nwosu', 'mirabel.nwosu@ncs-eko2026.local', 'delegate', NULL),
('Abisola Ogooluwa', 'abisola.ogooluwa@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Itse E Ajuyah', 'itse.ajuyah@ncs-eko2026.local', 'delegate', NULL),
('Dr Chibuike Okorie', 'chibuike.okorie@ncs-eko2026.local', 'delegate', NULL),
('Dr Maryam Lawal Makarfi', 'maryam.makarfi@ncs-eko2026.local', 'delegate', NULL),
('Dr CHUKWUEBUKA ELE', 'chukwuebuka.ele@ncs-eko2026.local', 'delegate', NULL),
('Dr Chukwunonso Chukwunenye', 'chukwunonso.chukwunenye@ncs-eko2026.local', 'delegate', NULL),
('Dr Omokorede Ademowo-Olusanya', 'omokorede.ademowo-olusanya@ncs-eko2026.local', 'delegate', NULL),
('CHIGOZIE CHARLES EKENGWU', 'chigozie.ekengwu@ncs-eko2026.local', 'delegate', NULL),
('Peter Abioye', 'peter.abioye@ncs-eko2026.local', 'guest', 'Medical Student'),
('Dr Mohamed Abu Nada', 'mohamed.nada@ncs-eko2026.local', 'delegate', NULL),
('Dr Reichmann Uzoma', 'reichmann.uzoma@ncs-eko2026.local', 'delegate', NULL),
('Dr Prince Amadi', 'prince.amadi@ncs-eko2026.local', 'delegate', NULL),
('Dr Chibuike Ozor', 'chibuike.ozor@ncs-eko2026.local', 'delegate', NULL),
('MAYODE JAYEOLA', 'mayode.jayeola@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Emmanuel Edafe', 'emmanuel.edafe@ncs-eko2026.local', 'delegate', NULL),
('Hauwa Bako', 'hauwa.bako@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Abdulmalik Garba', 'abdulmalik.garba@ncs-eko2026.local', 'delegate', NULL),
('Dr Sadiya Salele Iro', 'sadiya.iro@ncs-eko2026.local', 'delegate', NULL),
('Dr. OLADIPUPO OLAYIWOLA FASAN', 'oladipupo.fasan@ncs-eko2026.local', 'delegate', NULL),
('Dr. Josephine Etieyibo', 'josephine.etieyibo@ncs-eko2026.local', 'delegate', NULL),
('Dr Ayotunde Raheem', 'ayotunde.raheem@ncs-eko2026.local', 'delegate', NULL),
('Dr Umar Ibrahim Abba', 'umar.abba@ncs-eko2026.local', 'delegate', NULL),
('Abraham Awe', 'abraham.awe@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Ifeanyichukwu Agu', 'ifeanyichukwu.agu@ncs-eko2026.local', 'delegate', NULL),
('Dr Fatima Al-Hassan', 'fatima.al-hassan@ncs-eko2026.local', 'delegate', NULL),
('DR VICTOR NYEMA', 'victor.nyema@ncs-eko2026.local', 'delegate', NULL),
('Greatness Eyenor', 'greatness.eyenor@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Chibundo Onyia', 'chibundo.onyia@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Michael Ochem', 'michael.ochem@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Adedoyin Olowookere', 'adedoyin.olowookere@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Oluwole Adeoye', 'oluwole.adeoye@ncs-eko2026.local', 'delegate', NULL),
('Oluwabukola Akindoyin', 'oluwabukola.akindoyin@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Aniedi Victor', 'aniedi.victor@ncs-eko2026.local', 'delegate', NULL),
('Dr Ishaku Sawa', 'ishaku.sawa@ncs-eko2026.local', 'delegate', NULL),
('Margreth E Aba', 'margreth.aba@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Olabimpe Lamai', 'olabimpe.lamai@ncs-eko2026.local', 'delegate', NULL),
('Wasilat Anafi', 'wasilat.anafi@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Mayowa Obawole', 'mayowa.obawole@ncs-eko2026.local', 'delegate', NULL),
('Somtochukwu Mbama', 'somtochukwu.mbama@ncs-eko2026.local', 'guest', 'Medical Student'),
('Dr Julius Edeogu', 'julius.edeogu@ncs-eko2026.local', 'delegate', NULL),
('Oreoluwa Oseni', 'oreoluwa.oseni@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Okoro Chinatu Anita', 'chinatu.anita@ncs-eko2026.local', 'exhibitor', 'Allied'),
('Dr Hafsat Mijinyawa', 'hafsat.mijinyawa@ncs-eko2026.local', 'guest', 'Associate'),
('Dr Taiwo Bambgoye', 'taiwo.bambgoye@ncs-eko2026.local', 'delegate', NULL),
('Prof Michael Olabode Balogun', 'michael.balogun@ncs-eko2026.local', 'delegate', NULL);
